# Generated by Django 4.2.6 on 2024-02-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_journalentry_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='mood',
            field=models.IntegerField(choices=[(1, '😔'), (2, '🙁'), (3, '😐'), (4, '🙂'), (5, '😄')], default=3),
        ),
    ]
