# Generated by Django 4.2.6 on 2024-02-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_journalentry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.IntegerField(choices=[(1, 'Very Sad 😔'), (2, 'Sad 🙁'), (3, 'Neutral 😐'), (4, 'Happy 🙂'), (5, 'Very Happy😄')], default=3),
        ),
    ]
