# Generated by Django 4.2.6 on 2024-03-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='favourited',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='permanently_deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='text',
            field=models.TextField(),
        ),
    ]
