# Generated by Django 4.2.6 on 2024-03-27 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('user_id', 'name')},
        ),
    ]
