# Generated by Django 4.2.6 on 2024-03-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('questions', models.CharField(blank=True, max_length=255)),
                ('user_entry', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
