# Generated by Django 4.2.6 on 2024-02-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='combined_answers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
