# Generated by Django 4.2.6 on 2024-02-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
