# Generated by Django 4.2.6 on 2024-03-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_user_email_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_is_verified',
        ),
    ]
