# Generated by Django 4.2.6 on 2024-03-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
