# Generated by Django 4.2.6 on 2024-03-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_userpreferences_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='opt_out',
            field=models.BooleanField(default=False),
        ),
    ]
