# Generated by Django 4.2.6 on 2024-01-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_days_to_journal',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
