# Generated by Django 4.2.6 on 2024-02-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_journalentry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.IntegerField(choices=[(1, '😔'), (2, '🙁'), (3, '😐'), (4, '🙂'), (5, '😄')], default=3, help_text='Please select how you are feeling from the dropdown below.'),
        ),
    ]
