# Generated by Django 4.2.6 on 2024-01-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_user_preferred_days_to_journal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_time_to_journal',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
