# Generated by Django 4.2.6 on 2024-01-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_user_preferred_days_to_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_days_to_journal',
            field=models.CharField(blank=True, choices=[(None, 'Days:'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=20, null=True),
        ),
    ]
