# Generated by Django 4.2.6 on 2024-02-15 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_userpreferences_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='number_of_times_to_journal',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
