# Generated by Django 4.2.6 on 2024-02-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_userpreferences_number_of_times_to_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='sunday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='wednesday',
            field=models.BooleanField(default=True),
        ),
    ]
