# Generated by Django 4.2.6 on 2024-02-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_userpreferences_friday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='number_of_times_to_journal',
        ),
    ]
