# Generated by Django 4.2.6 on 2024-02-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='favourited',
            field=models.BooleanField(default=False),
        ),
    ]
