# Generated by Django 4.2.6 on 2024-03-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
