# Generated by Django 4.2.6 on 2024-03-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_journalentry_favourited'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='permanently_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
